### ISSUE TITLE
Transform VGroup to TexMobject

### ISSUE THREAD

**Issue by lizongzeshunshun** [3b1b/manim#425] opened 2019-01-31 11:48 UTC
I'm new to manim and I want to transform a VGroup made up of several TexMobject to a single Tex
Mobject, however something unexpected happened.

This is my code

```
#!/usr/bin/env python

from big_ol_pile_of_manim_imports import *

class SumDC(Scene):
    def construct(self):
        list1 = TexMobject(r"1+2+3+4+\cdots +n=?")
        list2 = TexMobject(r"a_1+a_2+a_3+a_4+\cdots +a_n=?")
        desc = TexMobject(r"a_{n+1}-a_n=d")
        
        min1 = TexMobject(r"a_2-a_1=d")
        min1.shift(2 * UP)
        min2 = TexMobject(r"a_3-a_2=d")
        min2.next_to(min1, DOWN)
        min3 = TexMobject(r"a_4-a_3=d")
        min3.next_to(min2, DOWN)
        min4 = TexMobject(r"\cdots")
        min4.next_to(min3, DOWN)
        min5 = TexMobject(r"a_n-a_{n-1}=d")
        min5.next_to(min4, DOWN)
        minn = VGroup(min1, min2, min3, min4, min5)
        
        summ = TexMobject(r"a_n-a_1=\left( n-1 \right) d") 
        summ2 = TexMobject(r"a_n=a_1+\left( n-1 \right) d")
        
        self.play(Write(list1))
        self.wait(2)
        self.play(Transform(list1, list2))
        self.wait(2)
        self.play(ApplyMethod(list1.shift, 3 * UP))
        self.play(Write(minn))
        self.wait(2)
        self.play(Transform(minn, summ))
        self.wait(2)
        self.play(Transform(minn, summ2))
```

After transforming the image looks like this

![image](https://user-images.githubusercontent.com/10304206/52052373-12f45980-2591-11e9-8876-04d526f71461.png)

How can I solve the problem? Thank you.

**Comment by lizongzeshunshun** [comment] 2019-01-31 12:36
Find a solution.
```
        summ = TexMobject(r"a_n-a_1=\left( n-1 \right) d") 
        summ2 = TexMobject(r"a_n=a_1+\left( n-1 \right) d")
```
Change to 
```
        summ = VGroup(TexMobject(r"a_n-a_1=\left( n-1 \right) d") )
        summ2 = VGroup(TexMobject(r"a_n=a_1+\left( n-1 \right) d"))
```

But I'm still why can't a VGroup be directly changed to a TexMobject.

**Comment by 3b1b** [comment] 2019-02-02 06:32
This is a bug, I think caused by the fact that interpolating between paths that involve subpaths (like letters with holes in them), does not work well between groups with different hierarchies.   This should, of course, be fixed, but the reason your fixes work is because the straighten out the hierarchies of the source and target groups.

**Comment by 3b1b** [comment] 2019-02-12 04:53
I believe this issue is now fixed with some of the latest changes.

**Closed** 2019-02-12 04:54 UTC
Labels: bug
