### ISSUE TITLE
Installation of Manim tutorial by Theorem of Beethoven on Mac

### ISSUE THREAD

**Issue by RichardBot7000** [3b1b/manim#647] opened 2019-07-23 03:13 UTC
Hello everyone,
I followed the steps on Theorem of Beethoven's video on how to install Manim on Mac. I got up to this part where I had to paste
python3 -m pip install -r requirements.txt
However, when I try to paste that in, I get the following message.
![Screen Shot 2019-07-22 at 8 07 48 PM](https://user-images.githubusercontent.com/32045107/61679855-79467300-acbc-11e9-8d08-5537b2cd31d7.jpg)
I did get some warnings before this step, and I can include screenshots of them if it is necessary. Any help would be appreciated. Thanks!

**Comment by Elteoremadebeethoven** [comment] 2019-07-23 03:33
Try this:
https://github.com/3b1b/manim/issues/524#issuecomment-489093651

**Comment by RichardBot7000** [comment] 2019-07-23 03:42
I got 
sh: latex: command not found
when typing in 
python3 -m manim example_scenes.py WriteStuff -pl

**Comment by Elteoremadebeethoven** [comment] 2019-07-23 03:57
Reinstall MacTeX, if that does not work then install TeXMaker and build the manimlib/tex_template.tex and run manim again.

**Comment by RichardBot7000** [comment] 2019-07-23 03:59
Should I go through the same process in the video after installing it?

**Comment by Elteoremadebeethoven** [comment] 2019-07-23 04:06
Only for Mactex

**Comment by Elteoremadebeethoven** [comment] 2019-07-23 04:08
Try this before https://stackoverflow.com/questions/13916273/after-upgrade-to-osx-10-8-2-latex-command-not-found

**Comment by RichardBot7000** [comment] 2019-07-23 04:09
How do I uninstall Mactex? When I tried to delete the folder from the applications folder, it only took up 113 MB of space, when Mactex installer says it takes up 6.96 GB of space. I think I am not deleting the entire application.

**Comment by Elteoremadebeethoven** [comment] 2019-07-23 04:15
Before to reinstall MacTeX try that link

**Comment by RichardBot7000** [comment] 2019-07-23 04:32
I tried that link but it didn't work. I also reinstalled MacTeX. Do I have to reinstall PIP, FFmpeg, SoX, and Cairo?

**Comment by Elteoremadebeethoven** [comment] 2019-07-23 04:36
No, only mactex

**Comment by RichardBot7000** [comment] 2019-07-23 04:38
alright I did that, but I tried 
python3 -m manim example_scenes.py WriteStuff -pl
again yet it still doesn't work

**Comment by Elteoremadebeethoven** [comment] 2019-07-23 04:42
Install Texmaker, then open tex_template.tex from manimlib using Texmaker and a build it, you can se tutoriales in youtube, that have to generate a pdf file that says "YoutTextHere", if that happen then try run manim again

**Comment by RichardBot7000** [comment] 2019-07-23 04:50
Do you recommend any tutorials for me to watch?

**Comment by Elteoremadebeethoven** [comment] 2019-07-23 05:26
The truth is quite simple, just open the file, and click on the arrow to the left of "Quick build". But first try using the command

```
python3 -m pip install latex
```

If it doesn't work then do the texmkaer thing

**Comment by RichardBot7000** [comment] 2019-07-23 06:14
I got the below warning, and the WriteStuff command still doesn't work. When I clicked the arrow to the left of Quick build, a popup appears that says "Can't detect file name"

 WARNING: The scripts futurize and pasteurize are installed in '/Library/Frameworks/Python.framework/Versions/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by RichardBot7000** [comment] 2019-07-23 06:21
The YourTextHere works, and I tried running "python3 -m manim example_scenes.py WriteStuff -pl" again. However, I still got the error:
![image](https://user-images.githubusercontent.com/32045107/61687433-4198f480-acd7-11e9-9bc6-49ee82829fd0.png)

**Comment by Elteoremadebeethoven** [comment] 2019-07-23 06:36
Do not add the --use-clang, in your case that attribute does not work.

The problem is that manim is not using all latex packages at the time of execution, this problem had already been presented in #564 but in Windows. Sorry, I can't help you anymore because I'm not a Mac expert, but you can join the manim community in [Discord](https://discord.gg/mMRrZQW), also post it in [stackoverflow](https://stackoverflow.com/questions/tagged/manim) and [Reddit](https://www.reddit.com/r/manim/), in this way more people can see it, when you post your problem, the content also must have the .log file, which in your case you can see at the end of the image you uploaded (47f7 ... log). When the problem is resolved please post the solution here so that people who may have this error can see it.

**Comment by RichardBot7000** [comment] 2019-07-23 06:39
Alright, thanks for your help! I'll definitely check out the rest of your channel and recommend it to people!

**Comment by Elteoremadebeethoven** [comment] 2019-07-24 23:17
Hey, try this `brew cask install mactex`

**Comment by RichardBot7000** [comment] 2019-07-26 19:08
I tried that at first and it didn't work, but after I restarted my computer everything seemed to be working perfectly! Thanks for all the help!

**Comment by Elteoremadebeethoven** [comment] 2019-07-27 23:32
Perfect, then you can close the issue please.

**Closed** 2020-10-01 04:44 UTC
