### ISSUE TITLE
 program ok,but the video just black screen

### ISSUE THREAD

**Issue by donglx2004** [3b1b/manim#170] opened 2018-03-22 07:26 UTC
I run the program ok,but the video just black screen ,how can I fix it ?

**Comment by pu17** [comment] 2018-03-26 06:26
my program also have the same problem,but I don’t know how to fix it

**Comment by MedNait** [comment] 2018-03-28 20:49
Got the same problem too, black screen with no sound, even though there are no apparent errors! I tried on both windows and ubuntu and got the same result.

**Comment by fusir** [comment] 2018-03-31 01:47
Same.

`file` gives me `1080p60: ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]`

For another working mp4 I get `ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]`

The same so investigating if the file is corrupted at least the header isn't.

**Comment by fusir** [comment] 2018-03-31 01:51
See this issue: https://github.com/3b1b/manim/issues/119

Apparently using docker creates this problem.  I was using docker.  Unfortunately using arch its default python3-ness is a bitch with dependencies that haven't learned that `print(` is superior to `print`.

**Comment by fusir** [comment] 2018-03-31 04:29
Sorry to dominate this thread but I've solved the issue.

The issue is that particular animation is black on black.
See: https://ipfs.io/ipfs/QmYc9mCqPRtmw9GcSQckaB1RGNgSoqGJLWdEo4VMHbzg42/vidw8.mp4

I saved the pngs and used `convert` to change the alpha channel to white and then passed it into ffmpeg.

For reference:
```
for i in {1..180}
do
 convert frame$i.png -background white -alpha remove wframe$i.png
done
```
```
for i in {0..180}
do 
 cat wframe$i.png; 
done | ffmpeg -i - -c:a acc -c:v libx264 -crf 28 -tune animation -preset veryslow -pix_fmt yuv420p vidw.mp4
```

**Comment by pu17** [comment] 2018-04-03 07:08
Sorry, as you said docker creates this problem. so I uninstall docker from my computer and it still black screen with no error! how can I fix it

**Comment by pu17** [comment] 2018-04-03 07:16
Sorry, as I am not very good at English, maybe I misundersstand you words  before

**Comment by burlito** [comment] 2018-04-21 04:11
Hi,

Actually, I hit same issue, and with little bisecting It seems to be problem in aggdraw library, commit 242f55 https://github.com/pytroll/aggdraw/commit/183299329e8bbfcc5bbc280da492cc0a2c242f55

It seems that they are already aware about issue, https://github.com/pytroll/aggdraw/issues/20 ,
In meanwhile workaround is install aggdraw without commit  2c242f55 (lowe than 1.3 version)

**Comment by eulertour** [comment] 2018-11-27 19:54
Closing, as this issue no longer seems to be present.

**Closed by eulertour** 2018-11-27 19:54 UTC
