### ISSUE TITLE
Curve creation including y variable

### ISSUE THREAD

**Issue by JimChr-R4GN4R** [3b1b/manim#1229] opened 2020-09-16 12:53 UTC
I have this script:
```
from manimlib.imports import *
import numpy as np 

class graphx(GraphScene):
	CONFIG={
		"x_min": -4,
		"x_max": 4,
		"y_min": -2,
		"y_max": 2,
		"x_axis_label": "$x$",
		"y_axis_label": "$y$",
		"graph_origin": 0.5 * DOWN + 0 * LEFT,
	}

	# Defining graph functions 
	def show_function_graph(self): 
		self.setup_axes(animate=True)
		# Math function
		def func(x):
			return x**3 + 497*x + 1768
		#sin graph
		graph_sin=self.get_graph(func,x_min=-5, x_max=5)
		graph_sin.set_color(RED)
		# Cos graph

		
		# Play grapgs
		self.play(ShowCreation(graph_sin,), run_time=3)
		self.wait(1)
		# self.play(ShowCreation(graph_cos), run_time=3)



	# Defining construction
	def construct(self):
		self.show_function_graph()
```

and what I am trying to do is to show this curve: `y^2 = x^3 + 497*x + 1768`.
Have tried to math.sqrt(x**3 + 497*x + 1768), but it doesn't work.
Is there any way that I can include `y` variable?

**Comment by Level-314** [comment] 2020-09-17 01:41
Hi Jim, as a general rule, it is best to explicitly state what is going wrong. "It doesn't work" is quite broad.

I am guessing what is happening is that you are getting a math domain error. This has little to do with Manim. It is just that you are trying to use math.sqrt on a negative number. The result will be a complex number (i.e. it will have a non zero coeficient for _i_).

**Comment by NeoPlato** [comment] 2020-09-17 07:27
Your dilemma needs some serious math to be solved. Let's dive in.

We start off by admitting that computers exist and if you're going to hassle a graph in Manim at least get some help. Say, Desmos for example.

Your example is **wayyy** too complicated so I'm shrinking it down a bit.

![image](https://user-images.githubusercontent.com/67624028/93431688-29b60400-f8cd-11ea-8874-049a6830f641.png)

Great! Now let's think through this a bit.

For any x value you give me, can I determine the y value that is on that graph? Let's see!

![image](https://user-images.githubusercontent.com/67624028/93432142-c8426500-f8cd-11ea-868a-eaa57353c4c3.png)

Yes...and no.
Not all x values work(orange line) and even for those that do(purple line) you have to account for two solutions which is not very helpful.

The reverse is feasible though. Any y value gives you one and only one x value, Except it pushes you to do something less efficient and objectively worse: solving this equation:

> x**3 + 2x + 1 = _something_

And not just for any specific something, which is doable by hand, but every point in the y range available. The good thing about this, however, is being able to represent that as a parametric equation which is already Manim programmed.

> This is a good time to tell you that Desmos is an already existing graphing calculator and for this case using Manim is overkill. But you asked the question and I have decided to answer.

```
from scipy.optimize import fsolve

class ImplicitGraph(Scene):
    def construct(self):
        plane = NumberPlane().add_coordinates()
        graph = plane.get_parametric_curve(
            self.implicit_curve(),
            t_min = plane.y_min,
            t_max = plane.y_max,
            color = YELLOW,
            stroke_width = 2
        )
        self.add(plane, graph)
        self.wait(2)
        
    def implicit_curve(self):
        #Don't worry about the initial approach mate, we're still solving y**2 = x**3 + 2x - 1
        func = lambda x: x**3 + 2*x - 1
        
        def parametric_function(t):
            #Proper math coming up
            func_to_solve = lambda x: func(x) - t**2
            x_part = RIGHT * fsolve(func_to_solve, 3) #3 is an arbitrary choice, only need a starting guess
            y_part = UP * t
            return x_part + y_part
        
        return parametric_function
```

![image](https://user-images.githubusercontent.com/67624028/93434121-67685c00-f8d0-11ea-9ccb-99022c5c5911.png)

You tell me if that's worth the effort.

**Comment by Level-314** [comment] 2020-09-17 13:22
NeoPlato - for the specific question mentioned by the OP, complex numbers are needed.

Though I do agree parametric equations are the way to go for a more generalized approach to graphing y^2 = x^3.... type equations.

One of my favorite small manim projects was resolving just such a parametric equation issue:
https://www.youtube.com/watch?v=zReqQ8NMsI0

**Comment by NeoPlato** [comment] 2020-09-17 13:55
Wow Mr. Level 100π

What Manim mastery

>If you didn't see it that was a name suggestion for your channel, something pronounced like "level hundred pi"

**Comment by NeoPlato** [comment] 2020-09-17 14:07
Interesting. Although I don't fully understand what you mean so you're open to share your solution as well.

Also, nice channel😃

**Comment by JimChr-R4GN4R** [comment] 2020-09-17 23:49
@NeoPlato Thanks for your information!

But I get an error when trying to render the script you give me...
This is the script:
```
class ImplicitCurve(Scene): 
	def construct(self):

		plane = NumberPlane().add_coordinates()
		graph = plane.get_parametric_curve(
			self.implicit_curve(),
			t_min = plane.y_min,
			t_max = plane.y_max,
			color = YELLOW,
			stroke_width = 2
			)
		self.add(plane,graph)
		self.wait(2)

		def implicit_curve(self):
			func = lambda x: x**3 + 2*x -1

			def parametric_function(t):
				func_to_solve = lambda x: func(x) - t**2
				x_part = RIGHT*fsolve(func_to_solve,3)
				y_part = UP*t
				return x_part + y_part

			return parametric_function
```

and I get this error:
```
Traceback (most recent call last):
  File "D:\Manim\manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "D:\Manim\manim\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "tutorial\test.py", line 16, in construct
    self.implicit_curve(),
AttributeError: 'ImplicitCurve' object has no attribute 'implicit_curve'
```

**Comment by NeoPlato** [comment] 2020-09-18 04:51
Mate

Push the code block containing the method _implicit curve_ one level of indentation lower. The way I see it you've placed it in the _construct_ block hence it couldn't be initialized as an attribute of the scene class.

**Comment by JimChr-R4GN4R** [comment] 2020-09-18 05:19
Thank you @NeoPlato !

**Comment by Level-314** [comment] 2020-09-18 17:13
> Interesting. Although I don't fully understand what you mean so you're open to share your solution as well.
> 
> Also, nice channel😃

I see the issue is closed now but what I meant was that in the OP he said the equation was:
y**2 = x**3 + 497*x + 1768

The graph started at x = -4; filling that in to the equation you get y**2 =  -284

If you use math.sqrt(-284) you're going to get an error because math.sqrt() doesn't deal with complex numbers. (i.e. numbers with an _imaginary_ component _i_ where _i_**2 = -1)

The OP left a cryptic message "but it doesn't work." without explaining exactly what is meant by that. But I am certain that he would at least get a domain error if trying to use math.sqrt() on his original equation.

In order to get results with y**2 = negative number, he needs to use cmath. And in order to plot them, he needs to include a 3rd dimension.

**Comment by JimChr-R4GN4R** [comment] 2020-09-18 17:56
@Level-314 Could you please share a script with your solution too? :)

**Comment by JimChr-R4GN4R** [comment] 2020-09-22 17:20
@NeoPlato Have tried to use your solution and it's working,but I cannot find a way to make it work with no `plane`.
What I am trying to do is to replace the `plane` with `setup_axes`.

![utttttttttttttttttttttttt](https://user-images.githubusercontent.com/59511698/93915173-478dc980-fd10-11ea-8fe7-53a34d0b792b.png)

This is the code I made to try to do this which does not working:
```
class ImplicitCurve(GraphScene):
	CONFIG = {
	"x_min" : -50,
	"x_max" : 50,
	"y_min" : -50,
	"y_max" : 50,
	"x_tick_frequency" : 25,
	"y_tick_frequency" : 25,
	"x_labeled_nums" : range(-50,51,25),
	"y_labeled_nums" : range(-50,51,25),
	"graph_origin" : ORIGIN ,
	"function_color" : RED ,
	"axes_color" : GREEN,
	 
	} 
	def construct(self):
		plane = self.setup_axes(animate=True)
		graph = plane.get_parametric_curve(
					self.implicit_curve(),
					t_min = -50,
					t_max = 50,
					color = YELLOW,
					)
		self.wait(2)

	def implicit_curve(self):
		func = lambda x: x**3 + 2*x -1

		def parametric_function(t):
			func_to_solve = lambda x: func(x) - t**2
			x_part = RIGHT*fsolve(func_to_solve,0)
			y_part = UP*t
			return x_part + y_part

		return parametric_function
```

**Comment by NeoPlato** [comment] 2020-09-22 18:27
So let's clear two things real quick.

```
from scipy.optimize import fsolve

class Implicit2(GraphScene):
    CONFIG = {
        "x_min" : -50,
        "x_max" : 50,
        "y_min" : -50,
        "y_max" : 50,
        "x_tick_frequency" : 25,
        "y_tick_frequency" : 25,
        "x_labeled_nums" : range(-50,51,25),
        "y_labeled_nums" : range(-50,51,25),
        "graph_origin" : ORIGIN ,
        "function_color" : RED ,
        "axes_color" : GREEN,
    } 
    
    def construct(self):
        self.setup_axes(animate=True)
        graph = self.get_parametric_curve(
            self.implicit_curve(),
            t_min = -50,
            t_max = 50,
            color = YELLOW,
        )
        self.add(graph)       #Note this right here
        self.wait(2)

    def implicit_curve(self):
        func = lambda x: x**3 + 2*x -1

        def parametric_function(t):
            func_to_solve = lambda x: func(x) - t**2
            x_part = RIGHT * fsolve(func_to_solve, 0)
            y_part = UP * t
            return x_part + y_part

        return parametric_function
    
    def get_parametric_curve(
        self, func,
        color=None,
        t_min=None,
        t_max=None,
        **kwargs
    ):
        if color is None:
            color = next(self.default_graph_colors_cycle)
        if t_min is None:
            t_min = self.y_min
            #Brother
            ##This self.y_min merely accomodates with ease the arbitrary choices we discussed earlier
        if t_max is None:
            t_max = self.y_max
            #You get it
            ##I hack problems, not generalize them

        def parameterized_function(alpha):
            t = interpolate(t_min, t_max, alpha)   #Parameter for the :) parametric function
            x, y, _ = func(t)                      #This line assumes you use Manim's default 3D np arrays
            if not np.isfinite(y):
                y = self.y_max
            return self.coords_to_point(x, y)

        graph = ParametricFunction(
            parameterized_function,
            color=color,
            **kwargs
        )
        graph.underlying_function = func
        return graph
```

Before you copy this code and head on your merry way hear me out for a bit.

Your original version assumed that the `setup_axes` method of the `GraphScene` class returned the actual axes shown there; however those are two literal NumberLines stacked onto each other if you never noticed. Curious why that's the case but I have no right to judge a fellow coder's mental state, and I'll modify it in my laptop folder when I feel like it.

Honestly there are two ways to handle that

1. Make `setup_axes` return actual `Axes` in order for you to use them as you intended. I thought of this but then I saw already implemented `coords_to_point` that were used for the original `get_graph` method and in my unique fashion of solving only the problem at hand I decided to go with:

2. Implement a `get_parametric_function` method in an inherited class of `GraphScene` or in the original code itself. I copy pasted most of the structure from `get_graph` mainly because the coordinate_to_point thing already there was kinda genius and I'm inherently lazy. I do see why the `#TODO` comment still persists as this messiness indeed hints as reimplementing `GraphScene` entirely. But hey, who's editing the _master_ branch anyway?

Lastly, about the communication thing.

> I am a ghost merely because I can be so I'm not on any of those platforms. However, if I do change my mind, you'll be one of the first to know.
>> Also inspect the main library code yourself once in a while. It'll save you the effort of creating new issues every time you get stuck.
>>> And, how comfortable are you with Python? If you're making something a good understanding of Python's framework will go a long way.

**Closed** 2020-09-22 18:50 UTC
