### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by samsamson33** [3b1b/manim#214] opened 2018-04-18 15:33 UTC
When attempting to run the example code using 
`python extract_scene.py example_scenes.py SquareToCircle -pl`, 

I get the following error:

```
Traceback (most recent call last):
  File "extract_scene.py", line 269, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "extract_scene.py", line 159, in handle_scene
    sp.call(commands, stdout=FNULL, stderr=sp.STDOUT)
  File "C:\Python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by burlito** [comment] 2018-04-21 04:30
Hi,

Same error showed to me today, I sys sysscall tracing and problem was that I wasn't have ffmpeg installed.

So try to install ffmpeg, if that didn't help, try to do system call tracing.

**Comment by kiocosta** [comment] 2018-04-23 05:39
I have the same issue. 

ffmpeg is fine, I guess:
`C:\Users\sNAke\Desktop\manim-master\manim-master>ffmpeg -version
ffmpeg version N-87294-gec1573f Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 7.1.0 (GCC)
configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --ena
ble-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --en
able-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --
enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libf
reetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --e
nable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-
libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libs
nappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame
--enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx -
-enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-l
ibxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
libavutil      55. 75.100 / 55. 75.100
libavcodec     57.106.101 / 57.106.101
libavformat    57. 82.100 / 57. 82.100
libavdevice    57.  8.101 / 57.  8.101
libavfilter     6.105.100 /  6.105.100
libswscale      4.  7.103 /  4.  7.103
libswresample   2.  8.100 /  2.  8.100
libpostproc    54.  6.100 / 54.  6.100`

@burlito could you tell me how to do sys call tracing?

**Comment by angeloyeo** [comment] 2018-04-24 07:11
I found the same problem. (I also installed ffmpeg well... )

and I'm tyring to use it on Windows 10

I think the problem is explained in 

http://nikov-exploring.blogspot.kr/2017/12/the-manim-follow-up.html

The blog says that 

'The system cannot find the path specified is because it plays a chord when it finishes rendering a scene, you can find this method at the top of the helpers.py file: play_chord(*nums). **It tries to call a program play, which isn't installed on Windows.** '

So does this mean I can't use Manim on Windows?

**Comment by angeloyeo** [comment] 2018-04-24 10:55
I found this solution...

in extract_scene.py file

change the code in line 159

`sp.call(commands, stdout=FNULL, stderr=sp.STDOUT) 
`
into

`sp.call(commands, stdout=FNULL, stderr=sp.STDOUT, shell=True) 
`

**Comment by tsam1307** [comment] 2018-09-15 20:39
@angeloyeo It works fine except the misleading end message: "The system cannot find the path specified."

**Comment by eulertour** [comment] 2018-11-28 02:57
Closing, as this has been resolved.

**Closed by eulertour** 2018-11-28 02:57 UTC
