### ISSUE TITLE
"UserWarning: g0-65 not recognized" and wrong renderization of text

### ISSUE THREAD

**Issue by schneiderfelipe** [3b1b/manim#1239] opened 2020-09-29 00:23 UTC
Hi, I just installed manim from pip in Ubuntu 20.04.1 LTS (`$ sudo pip3 install manimlib`). I have a full stack TexLive installation (as of `$ sudo apt install texlive-full`), but it seems that I keep getting bad output from the `OpeningManimExample` in `example_scenes.py`. Specifically, I get the following output:

```
➜  ~ manim example_scenes.py -pl --leave_progress_bars
Media will be written to ./media/. You can change this behavior with the --media_dir flag.
1: FirstScene
2: OpeningManimExample
3: SquareToCircle
4: UpdatersExample
5: WarpSquare
6: WriteStuff

Choose number corresponding to desired scene/arguments.
(Use comma separated list for multiple entries)
Choice(s): 2
/usr/local/lib/python3.8/dist-packages/manimlib/mobject/svg/svg_mobject.py:125: UserWarning: g0-65 not recognized
  warnings.warn("%s not recognized" % ref)
Animation 0: WriteTextMobject, etc.: 100%|██████| 15/15 [00:00<00:00, 53.26it/s]
Animation 2: TransformTextMobject, etc.: 100%|██| 15/15 [00:00<00:00, 50.20it/s]
Animation 4: FadeOutTextMobject, etc.: 100%|████| 45/45 [00:01<00:00, 35.59it/s]
/usr/local/lib/python3.8/dist-packages/manimlib/mobject/svg/svg_mobject.py:125: UserWarning: g0-45 not recognized
  warnings.warn("%s not recognized" % ref)
/usr/local/lib/python3.8/dist-packages/manimlib/mobject/svg/svg_mobject.py:125: UserWarning: g0-108 not recognized
  warnings.warn("%s not recognized" % ref)
/usr/local/lib/python3.8/dist-packages/manimlib/mobject/svg/svg_mobject.py:125: UserWarning: g0-117 not recognized
  warnings.warn("%s not recognized" % ref)
Animation 6: MoveToTargetNumberPlane: 100%|█████| 45/45 [00:01<00:00, 23.13it/s]
Animation 8: TransformTextMobject: 100%|████████| 15/15 [00:00<00:00, 34.53it/s]

File ready at /home/schneider/media/videos/example_scenes/480p15/OpeningManimExample.mp4

Played 10 animations
```

Observe the bunch of `UserWarning: g0-65 not recognized` warnings that are coming from `svg_mobject.py`. Besides, I get weird output in two different pieces of text, see screenshots below:

![Captura de tela de 2020-09-28 21-20-55](https://user-images.githubusercontent.com/37125/94498471-9c2dba80-01d0-11eb-9eac-7dc1bc67d6b2.png)

![Captura de tela de 2020-09-28 21-21-15](https://user-images.githubusercontent.com/37125/94498480-a059d800-01d0-11eb-8115-b0628fc6b698.png)

**Comment by codingwithmagga** [comment] 2020-11-19 14:26
Hi I have the same issue on Ubuntu 20.04 too.
The conversion from dvi to svg seems to fail, but I couldn't figure out why.
My current workaround is to delete the "wrong" svg files and run the following command manually

```sh
dvisvgm 8c108d7b672013f3.dvi -n
```
where you have to replace the dvi file with the one you need.

**Comment by AEX-DOS** [comment] 2020-11-22 18:39
I have a similar issue with svg and also more error on indexing too. any idea what this is about: ```UserWarning: g0-104 not recognized```

**Comment by marcoschoos** [comment] 2020-11-23 08:03
@AEX-DOS it is the same issue schneiderfelipe mentioned. The conversions from dvi to svg fails or at least partly fails, and some letters, symbols etc. are not converted correctly. When manim is looking for that letter in the svg file it can't found it.  That produces the error. 
Remark: This doesn't have to be 100% correct, but I think in general that is what's happening here.  
One solution is to delete the "wrong/failed" svg file and convert it manually as I mentioned above.

Just be curious: Do you use Ubuntu 20.04 too?

**Comment by codingwithmagga** [comment] 2020-11-23 08:03
@AEX-DOS it is the same issue schneiderfelipe mentioned. The conversions from dvi to svg fails or at least partly fails, and some letters, symbols etc. are not converted correctly. When manim is looking for that letter in the svg file it can't found it. That produces the error.
Remark: This doesn't have to be 100% correct, but I think in general that is what's happening here.
One solution is to delete the "wrong/failed" svg file and convert it manually as I mentioned above.

Just be curious: Do you use Ubuntu 20.04 too?

**Comment by schneiderfelipe** [comment] 2020-11-23 11:51
That's weird. Shouldn't manim be able to do the same thing as manually converting the files? It sounds like this is some path/permission problem. What do you think, @codingwithmagga?

**Comment by codingwithmagga** [comment] 2020-11-23 12:33
In almost all cases it works. There are only a very few cases where it fails, at least on my computer. Sometimes it was enough to delete the *.svg and run manim again. The command from manim for dvisvgm looks like this

```
dvisvgm "/full_path_to_dvi/c4626eca017672c1.dvi" -n -v 0 -o "/full_path_to_dvi/Tex/c4626eca017672c1.svg" > /dev/null
```
-v 0 just suppress the output from dvisvgm
-o  defines the ouput

I have to say that this error didn't occur anymore in my case. I tried to install some additional fonts but I'm not sure if it really solves the problem or I'm just lucky now, because I wasn't able to recreate the error. 

I tried to follow my steps and these are some things I did:
* update dvisvgm
* install texlive-fonts-extra 
* install cm-super

**Comment by AEX-DOS** [comment] 2020-11-23 16:11
@codingwithmagga My error looks like this:

```C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-84 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-104 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-105 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-115 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-97 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-114 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-101 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-103 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-117 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-108 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-116 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\TYVM\manim\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-120 not recognized
  warnings.warn("%s not recognized" % ref)



Traceback (most recent call last):
  File "C:\Users\TYVM\manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\TYVM\manim\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "tutorial/1_text_format.py", line 5, in construct
    text = TextMobject("This is a regular text")
  File "C:\Users\TYVM\manim\manimlib\mobject\svg\tex_mobject.py", line 150, in __init__
    self.break_up_by_substrings()
  File "C:\Users\TYVM\manim\manimlib\mobject\svg\tex_mobject.py", line 190, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range```

**Comment by AEX-DOS** [comment] 2020-11-23 16:13
what kinda solution would you suggest. The svg folder is untouched and regarding the indexing idk how its out of range.
thanks

**Comment by marcoschoos** [comment] 2020-11-23 16:44
```python
def break_up_by_substrings(self):
        new_submobjects = []
        curr_index = 0
        config = dict(self.CONFIG)
        config["alignment"] = ""
        for tex_string in self.tex_strings:
            sub_tex_mob = SingleStringTexMobject(tex_string, **config)
            num_submobs = len(sub_tex_mob.submobjects)
            new_index = curr_index + num_submobs
            if num_submobs == 0:
                # For cases like empty tex_strings, we want the corresponing
                # part of the whole TexMobject to be a VectorizedPoint
                # positioned in the right part of the TexMobject
                sub_tex_mob.submobjects = [VectorizedPoint()]
                last_submob_index = min(curr_index, len(self.submobjects) - 1)
                sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
            else:
                sub_tex_mob.submobjects = self.submobjects[curr_index:new_index]
            new_submobjects.append(sub_tex_mob)
            curr_index = new_index
        self.submobjects = new_submobjects
        return self
```

Looking at the code it seems that your string is empty somehow. That would mean the conversion of your string "This is a regular text" seems to fail completely. My guess is that some latex installations are missing. Regarding to this page https://eulertour.com/docs/ it should be either:

```cl
apt install texlive-full
```
or this:

```cl
apt install  texlive texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science texlive-fonts-extra tipa
```

@schneiderfelipe I think I also installed the bottom ones too. But since you already habe a full installation I assume this couldn't be the reason for the error

**Comment by codingwithmagga** [comment] 2020-11-23 16:52
```python
def break_up_by_substrings(self):
        new_submobjects = []
        curr_index = 0
        config = dict(self.CONFIG)
        config["alignment"] = ""
        for tex_string in self.tex_strings:
            sub_tex_mob = SingleStringTexMobject(tex_string, **config)
            num_submobs = len(sub_tex_mob.submobjects)
            new_index = curr_index + num_submobs
            if num_submobs == 0:
                # For cases like empty tex_strings, we want the corresponing
                # part of the whole TexMobject to be a VectorizedPoint
                # positioned in the right part of the TexMobject
                sub_tex_mob.submobjects = [VectorizedPoint()]
                last_submob_index = min(curr_index, len(self.submobjects) - 1)
                sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
            else:
                sub_tex_mob.submobjects = self.submobjects[curr_index:new_index]
            new_submobjects.append(sub_tex_mob)
            curr_index = new_index
        self.submobjects = new_submobjects
        return self
```

Looking at the code it seems that your string is empty somehow. That would mean the conversion of your string "This is a regular text" seems to fail completely. My guess is that some latex installations are missing. Regarding to this page https://eulertour.com/docs/ it should be either:

```cl
apt install texlive-full
```
or this:

```cl
apt install  texlive texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science texlive-fonts-extra tipa
```

@schneiderfelipe I think I also installed the bottom ones too. But since you already habe a full installation I assume this couldn't be the reason for the error

**Comment by AEX-DOS** [comment] 2020-11-23 17:30
I use windows and shouldn't miktex already include texlive since its a latex distribution ?

**Comment by AEX-DOS** [comment] 2020-11-23 18:44
I will double check, but i thought the complete package from net installer fixed it :/

**Comment by codingwithmagga** [comment] 2020-11-24 06:40
The tex file manim generates looks like this

```tex
\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\DisableLigatures{encoding = *, family = * }
%\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

This is a regular text  

\end{document}

Maybe you can try to compile this one with latex out of manim to see whats happening. You should maybe also look in some dvi in svg files in  YOUR_MANIM_FOLDER/media/Tex and see how they look like and maybe post them here
```

**Comment by NeoPlato** [comment] 2020-11-29 11:18
What if you install all the remaining packages and see if that helps. Check out #1276

**Comment by Suji04** [comment] 2020-12-07 14:40
I was facing a similar issue.

`
...
line 190, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range
`

I solved this by reinstalling miktex and selecting "Ask me before installing new packages".

**Comment by joakimjalden** [comment] 2021-01-04 19:44
> In almost all cases it works. There are only a very few cases where it fails, at least on my computer. Sometimes it was enough to delete the *.svg and run manim again. The command from manim for dvisvgm looks like this
> 
> ```
> dvisvgm "/full_path_to_dvi/c4626eca017672c1.dvi" -n -v 0 -o "/full_path_to_dvi/Tex/c4626eca017672c1.svg" > /dev/null
> ```
> 
> -v 0 just suppress the output from dvisvgm
> -o defines the ouput
> 
> I have to say that this error didn't occur anymore in my case. I tried to install some additional fonts but I'm not sure if it really solves the problem or I'm just lucky now, because I wasn't able to recreate the error.
> 
> I tried to follow my steps and these are some things I did:
> 
> * update dvisvgm
> * install texlive-fonts-extra
> * install cm-super

I fixed the same issue on my Windows 10 installation with MiKTeX by installing the cm-super package (and was able to recreate the error by uninstalling the package). In my case, the issue was that the MiKTeX installation did not have the correct Type 1 fonts for the T1 encoding (as in \usepackage[T1]{fontenc}) and this caused dvisvgm to not be able to include the path attribute in the generated svg file (which is what the -n option to dvisvgm is supposed to do). This is what caused the "g0-65 not recognized" error in my case. cm-super comes with the correct Type 1 fonts for the T1 encoding.

**Comment by Nikhil-Work** [comment] 2021-03-09 01:39
Installing cm-super fixed the issue for me as well.

**Comment by HateFindingNames** [comment] 2021-04-14 10:44
Win10 19042, MikTeX CurrentVersion 21.1, SetupVersion 2.9

> I fixed the same issue on my Windows 10 installation with MiKTeX by installing the cm-super package (and was able to recreate the error by uninstalling the package)

Confirmed. Thanks :)

**Comment by TonyCrane** [comment] 2021-06-12 10:13
Maybe this issue has been solved? So closing this.

**Closed by TonyCrane** 2021-06-12 10:13 UTC
Labels: SVG
