### ISSUE TITLE
Incorrect graphing?

### ISSUE THREAD

**Issue by 6r1d** [3b1b/manim#1441] opened 2021-03-18 13:40 UTC
### Describe the bug
Manim's [`GraphScene`](https://docs.manim.community/en/v0.1.1/reference/manim.scene.graph_scene.GraphScene.html) output is showing some artefacts in one context: "calculating modulo of 1.0" or `x % 1.0`.

I'll compare it to GeoGebra, because I have a [GeoGebra](https://www.geogebra.org/calculator) tab open, it has a [mod command](https://wiki.geogebra.org/en/Mod_Command) and it shows a different result.

**Code**:
```python
from manim import *
import numpy as np

class PhaseValuePlot(GraphScene):
    def __init__(self, **kwargs):
        GraphScene.__init__(
            self,
            x_min=-3,
            x_max=3,
            num_graph_anchor_points=100,
            y_min=-2.0,
            y_max=2.0,
            graph_origin=ORIGIN,
            axes_color=WHITE,
            x_labeled_nums=range(-3, 3, 1),
            y_axis_label="Phase [p]",
            x_axis_label="Time [T]",
            **kwargs
        )
        self.function_color = BLUE

    def construct(self):
        self.setup_axes()
        func_graph = self.get_graph(lambda t: t % 1.0, x_min=-2, x_max=2, discontinuities=[1], color=self.function_color)
        phase_formula = MathTex(r"p = T \mod 1.0")
        phase_formula.next_to(func_graph, RIGHT + UP)

        self.play(ShowCreation(self.axes))
        self.play(Write(phase_formula))
        self.play(Write(func_graph))
        self.wait(3)
        self.play(FadeOut(func_graph))
        self.play(FadeOut(self.axes))
```

**Expected output**:
GeoGebra shows (I believe) a correct plot.

![](https://i.imgur.com/DzG0M42.png)

**Wrong display**:

There's some "ripple" on the function output I'd like to fix. Also, function output reaches values less than `0`.
Also, I don't mind the vertical lines.

![](https://i.imgur.com/pePUYQm.png)

### Additional context

I am not completely sure it's graphing and not some weird floating point operation, so that is the first thing to check here.

**Comment by NicolasCaous** [comment] 2021-03-18 13:54
I think this is an issue with the interpolation of the step function used to generate the graph. It's not a bug per se, it's just a "rounding error". The GraphScene expects a continuous function. In your case, since the function provided isn't continuous on the plotted interval, GraphScene still interpolated all steps as if they were continuous, generating your graph as a result.

You could increase the resolution of the step function. You would still see a vertical line, but it would look closer to its true value.

**Comment by NicolasCaous** [comment] 2021-03-18 14:15
Looking at the [parametric function source code](https://github.com/ManimCommunity/manim/blob/acb27db2c53bb533e2aee878302166058c6d598a/manim/mobject/functions.py#L15), maybe you should pass the `discontinuities` parameter to specify where the function is not continuous. (`GraphScene.get_graph` pass all given kwargs to the `ParametricFunction` constructor)

**Comment by 6r1d** [comment] 2021-03-18 14:20
Ripple persists.

If I'm using a `range` operator:

```python
func_graph = self.get_graph(lambda t: t % 1.0, x_min=-2, x_max=2, discontinuities=range(-4, 4, 1), color=self.function_color)
```

If I explicitly write:
```python
func_graph = self.get_graph(lambda t: t % 1.0, x_min=-2, x_max=2, discontinuities=[-4, -3, -2, -1, 0, 1, 2, 3, 4], color=self.function_color)
```

P.S.: I have a community version of Manim, so I recreated the issue [here](https://github.com/ManimCommunity/manim/issues/1126). I am not sure about 3b1b version, but it's worth checking!

**Comment by TonyCrane** [comment] 2021-06-12 09:18
I have checked it, and there is no such problem in 3b1b version. So closing this.

**Closed by TonyCrane** 2021-06-12 09:18 UTC
Labels: bug
